# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Nov 19 10:02:19 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(287, 271)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/tow_icon2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.dock_jog = QtGui.QDockWidget(self.centralWidget)
        self.dock_jog.setEnabled(True)
        self.dock_jog.setGeometry(QtCore.QRect(30, 60, 231, 71))
        self.dock_jog.setFloating(False)
        self.dock_jog.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dock_jog.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dock_jog.setObjectName(_fromUtf8("dock_jog"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.pbJogPendant = QtGui.QPushButton(self.dockWidgetContents)
        self.pbJogPendant.setGeometry(QtCore.QRect(10, 10, 75, 31))
        self.pbJogPendant.setCheckable(True)
        self.pbJogPendant.setObjectName(_fromUtf8("pbJogPendant"))
        self.pbJogPlus = QtGui.QPushButton(self.dockWidgetContents)
        self.pbJogPlus.setGeometry(QtCore.QRect(110, 10, 51, 31))
        self.pbJogPlus.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbJogPlus.setIcon(icon1)
        self.pbJogPlus.setIconSize(QtCore.QSize(24, 24))
        self.pbJogPlus.setObjectName(_fromUtf8("pbJogPlus"))
        self.pbJogMinus = QtGui.QPushButton(self.dockWidgetContents)
        self.pbJogMinus.setGeometry(QtCore.QRect(170, 10, 51, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbJogMinus.setIcon(icon2)
        self.pbJogMinus.setIconSize(QtCore.QSize(24, 24))
        self.pbJogMinus.setObjectName(_fromUtf8("pbJogMinus"))
        self.dock_jog.setWidget(self.dockWidgetContents)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 287, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuTraverse_Offset = QtGui.QMenu(self.menuOptions)
        self.menuTraverse_Offset.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.menuTraverse_Offset.setAcceptDrops(True)
        self.menuTraverse_Offset.setObjectName(_fromUtf8("menuTraverse_Offset"))
        self.menuAutomatic_Tweet = QtGui.QMenu(self.menuOptions)
        self.menuAutomatic_Tweet.setObjectName(_fromUtf8("menuAutomatic_Tweet"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuHoming = QtGui.QMenu(self.menuBar)
        self.menuHoming.setObjectName(_fromUtf8("menuHoming"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(22, 22))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_Jog = QtGui.QToolBar(MainWindow)
        self.toolBar_Jog.setEnabled(True)
        self.toolBar_Jog.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar_Jog.setMovable(False)
        self.toolBar_Jog.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar_Jog.setIconSize(QtCore.QSize(22, 22))
        self.toolBar_Jog.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar_Jog.setFloatable(False)
        self.toolBar_Jog.setObjectName(_fromUtf8("toolBar_Jog"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Jog)
        self.dock_ptp = QtGui.QDockWidget(MainWindow)
        self.dock_ptp.setMinimumSize(QtCore.QSize(287, 178))
        self.dock_ptp.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.dock_ptp.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dock_ptp.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dock_ptp.setObjectName(_fromUtf8("dock_ptp"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.rbRelative = QtGui.QRadioButton(self.dockWidgetContents_2)
        self.rbRelative.setGeometry(QtCore.QRect(30, 10, 71, 16))
        self.rbRelative.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rbRelative.setChecked(True)
        self.rbRelative.setObjectName(_fromUtf8("rbRelative"))
        self.pbGo = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pbGo.setGeometry(QtCore.QRect(120, 120, 61, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbGo.setIcon(icon3)
        self.pbGo.setIconSize(QtCore.QSize(21, 21))
        self.pbGo.setCheckable(False)
        self.pbGo.setAutoDefault(False)
        self.pbGo.setDefault(False)
        self.pbGo.setFlat(False)
        self.pbGo.setObjectName(_fromUtf8("pbGo"))
        self.rbAbsolute = QtGui.QRadioButton(self.dockWidgetContents_2)
        self.rbAbsolute.setGeometry(QtCore.QRect(110, 10, 71, 16))
        self.rbAbsolute.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rbAbsolute.setChecked(False)
        self.rbAbsolute.setObjectName(_fromUtf8("rbAbsolute"))
        self.groupBox_shortcuts = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_shortcuts.setGeometry(QtCore.QRect(210, 10, 61, 141))
        self.groupBox_shortcuts.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_shortcuts.setObjectName(_fromUtf8("groupBox_shortcuts"))
        self.pbGoRightLimit = QtGui.QPushButton(self.groupBox_shortcuts)
        self.pbGoRightLimit.setGeometry(QtCore.QRect(10, 100, 41, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/go-last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbGoRightLimit.setIcon(icon4)
        self.pbGoRightLimit.setIconSize(QtCore.QSize(22, 22))
        self.pbGoRightLimit.setObjectName(_fromUtf8("pbGoRightLimit"))
        self.pbGoPlatform = QtGui.QPushButton(self.groupBox_shortcuts)
        self.pbGoPlatform.setGeometry(QtCore.QRect(10, 20, 41, 31))
        self.pbGoPlatform.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/go-home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbGoPlatform.setIcon(icon5)
        self.pbGoPlatform.setIconSize(QtCore.QSize(22, 22))
        self.pbGoPlatform.setObjectName(_fromUtf8("pbGoPlatform"))
        self.pbGoLeftLimit = QtGui.QPushButton(self.groupBox_shortcuts)
        self.pbGoLeftLimit.setGeometry(QtCore.QRect(10, 60, 41, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/go-first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbGoLeftLimit.setIcon(icon6)
        self.pbGoLeftLimit.setIconSize(QtCore.QSize(22, 22))
        self.pbGoLeftLimit.setObjectName(_fromUtf8("pbGoLeftLimit"))
        self.pbHalt = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pbHalt.setGeometry(QtCore.QRect(40, 120, 61, 31))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/agt_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbHalt.setIcon(icon7)
        self.pbHalt.setIconSize(QtCore.QSize(20, 20))
        self.pbHalt.setObjectName(_fromUtf8("pbHalt"))
        self.accSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.accSpinBox.setGeometry(QtCore.QRect(120, 90, 62, 22))
        self.accSpinBox.setDecimals(3)
        self.accSpinBox.setMaximum(2.0)
        self.accSpinBox.setSingleStep(0.1)
        self.accSpinBox.setProperty("value", 0.5)
        self.accSpinBox.setObjectName(_fromUtf8("accSpinBox"))
        self.velSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.velSpinBox.setGeometry(QtCore.QRect(120, 60, 62, 22))
        self.velSpinBox.setDecimals(3)
        self.velSpinBox.setMaximum(3.0)
        self.velSpinBox.setSingleStep(0.1)
        self.velSpinBox.setProperty("value", 0.3)
        self.velSpinBox.setObjectName(_fromUtf8("velSpinBox"))
        self.posSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.posSpinBox.setGeometry(QtCore.QRect(120, 30, 62, 22))
        self.posSpinBox.setWrapping(False)
        self.posSpinBox.setDecimals(3)
        self.posSpinBox.setMinimum(-26.1)
        self.posSpinBox.setMaximum(26.1)
        self.posSpinBox.setSingleStep(0.1)
        self.posSpinBox.setObjectName(_fromUtf8("posSpinBox"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 61, 21))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.dock_ptp.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dock_ptp)
        self.traverseOff = QtGui.QAction(MainWindow)
        self.traverseOff.setCheckable(True)
        self.traverseOff.setMenuRole(QtGui.QAction.PreferencesRole)
        self.traverseOff.setObjectName(_fromUtf8("traverseOff"))
        self.traverse1m = QtGui.QAction(MainWindow)
        self.traverse1m.setCheckable(True)
        self.traverse1m.setChecked(True)
        self.traverse1m.setObjectName(_fromUtf8("traverse1m"))
        self.traverse2m = QtGui.QAction(MainWindow)
        self.traverse2m.setCheckable(True)
        self.traverse2m.setObjectName(_fromUtf8("traverse2m"))
        self.traverse3m = QtGui.QAction(MainWindow)
        self.traverse3m.setCheckable(True)
        self.traverse3m.setObjectName(_fromUtf8("traverse3m"))
        self.traverse4m = QtGui.QAction(MainWindow)
        self.traverse4m.setCheckable(True)
        self.traverse4m.setEnabled(True)
        self.traverse4m.setObjectName(_fromUtf8("traverse4m"))
        self.actionWiki = QtGui.QAction(MainWindow)
        self.actionWiki.setObjectName(_fromUtf8("actionWiki"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.traverseCustom = QtGui.QAction(MainWindow)
        self.traverseCustom.setCheckable(False)
        self.traverseCustom.setEnabled(False)
        self.traverseCustom.setObjectName(_fromUtf8("traverseCustom"))
        self.actionRunHoming = QtGui.QAction(MainWindow)
        self.actionRunHoming.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionRunHoming.setMenuRole(QtGui.QAction.TextHeuristicRole)
        self.actionRunHoming.setObjectName(_fromUtf8("actionRunHoming"))
        self.actionOverride = QtGui.QAction(MainWindow)
        self.actionOverride.setEnabled(True)
        self.actionOverride.setObjectName(_fromUtf8("actionOverride"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.enableAxis = QtGui.QAction(MainWindow)
        self.enableAxis.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/checkmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enableAxis.setIcon(icon8)
        self.enableAxis.setObjectName(_fromUtf8("enableAxis"))
        self.actionViewTowAxis = QtGui.QAction(MainWindow)
        self.actionViewTowAxis.setCheckable(True)
        self.actionViewTowAxis.setChecked(True)
        self.actionViewTowAxis.setObjectName(_fromUtf8("actionViewTowAxis"))
        self.actionViewTraverseAxes = QtGui.QAction(MainWindow)
        self.actionViewTraverseAxes.setCheckable(True)
        self.actionViewTraverseAxes.setChecked(False)
        self.actionViewTraverseAxes.setObjectName(_fromUtf8("actionViewTraverseAxes"))
        self.actionTurbine_Axis = QtGui.QAction(MainWindow)
        self.actionTurbine_Axis.setEnabled(False)
        self.actionTurbine_Axis.setObjectName(_fromUtf8("actionTurbine_Axis"))
        self.actionWave_Maker = QtGui.QAction(MainWindow)
        self.actionWave_Maker.setEnabled(False)
        self.actionWave_Maker.setObjectName(_fromUtf8("actionWave_Maker"))
        self.actionHalt = QtGui.QAction(MainWindow)
        self.actionHalt.setIcon(icon7)
        self.actionHalt.setObjectName(_fromUtf8("actionHalt"))
        self.actionJogPendant = QtGui.QAction(MainWindow)
        self.actionJogPendant.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/yellow_power.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJogPendant.setIcon(icon9)
        self.actionJogPendant.setObjectName(_fromUtf8("actionJogPendant"))
        self.actionTweet_On_PTP = QtGui.QAction(MainWindow)
        self.actionTweet_On_PTP.setCheckable(True)
        self.actionTweet_On_PTP.setObjectName(_fromUtf8("actionTweet_On_PTP"))
        self.actionTweet_On_Jog = QtGui.QAction(MainWindow)
        self.actionTweet_On_Jog.setCheckable(True)
        self.actionTweet_On_Jog.setObjectName(_fromUtf8("actionTweet_On_Jog"))
        self.actionTweet_On_Enable_Disable = QtGui.QAction(MainWindow)
        self.actionTweet_On_Enable_Disable.setCheckable(True)
        self.actionTweet_On_Enable_Disable.setObjectName(_fromUtf8("actionTweet_On_Enable_Disable"))
        self.menuTraverse_Offset.addAction(self.traverseOff)
        self.menuTraverse_Offset.addAction(self.traverse1m)
        self.menuTraverse_Offset.addAction(self.traverse2m)
        self.menuTraverse_Offset.addAction(self.traverse3m)
        self.menuTraverse_Offset.addAction(self.traverse4m)
        self.menuTraverse_Offset.addAction(self.traverseCustom)
        self.menuAutomatic_Tweet.addAction(self.actionTweet_On_PTP)
        self.menuAutomatic_Tweet.addAction(self.actionTweet_On_Jog)
        self.menuAutomatic_Tweet.addAction(self.actionTweet_On_Enable_Disable)
        self.menuOptions.addAction(self.menuTraverse_Offset.menuAction())
        self.menuOptions.addAction(self.menuAutomatic_Tweet.menuAction())
        self.menuAbout.addAction(self.actionWiki)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menuHoming.addAction(self.actionRunHoming)
        self.menuHoming.addAction(self.actionOverride)
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHoming.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.enableAxis)
        self.toolBar.addAction(self.actionHalt)
        self.toolBar_Jog.addAction(self.actionJogPendant)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.rbAbsolute, self.rbRelative)
        MainWindow.setTabOrder(self.rbRelative, self.posSpinBox)
        MainWindow.setTabOrder(self.posSpinBox, self.velSpinBox)
        MainWindow.setTabOrder(self.velSpinBox, self.accSpinBox)
        MainWindow.setTabOrder(self.accSpinBox, self.pbHalt)
        MainWindow.setTabOrder(self.pbHalt, self.pbGo)
        MainWindow.setTabOrder(self.pbGo, self.pbGoLeftLimit)
        MainWindow.setTabOrder(self.pbGoLeftLimit, self.pbGoPlatform)
        MainWindow.setTabOrder(self.pbGoPlatform, self.pbGoRightLimit)
        MainWindow.setTabOrder(self.pbGoRightLimit, self.pbJogPendant)
        MainWindow.setTabOrder(self.pbJogPendant, self.pbJogPlus)
        MainWindow.setTabOrder(self.pbJogPlus, self.pbJogMinus)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Tow", None))
        self.dock_jog.setWindowTitle(_translate("MainWindow", "Jog Motion", None))
        self.pbJogPendant.setText(_translate("MainWindow", "Pendant", None))
        self.pbJogPlus.setToolTip(_translate("MainWindow", "Jog Left", None))
        self.pbJogMinus.setToolTip(_translate("MainWindow", "Jog Right", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Settings", None))
        self.menuTraverse_Offset.setTitle(_translate("MainWindow", "Traverse Offset", None))
        self.menuAutomatic_Tweet.setTitle(_translate("MainWindow", "Automatic Tweeting", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.menuHoming.setTitle(_translate("MainWindow", "Homing", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_Jog.setWindowTitle(_translate("MainWindow", "toolBarJog", None))
        self.toolBar_Jog.setToolTip(_translate("MainWindow", "Jog Toolbar", None))
        self.dock_ptp.setWindowTitle(_translate("MainWindow", "Point-to-Point Motion", None))
        self.rbRelative.setText(_translate("MainWindow", "Relative:", None))
        self.pbGo.setToolTip(_translate("MainWindow", "Go (Ctrl+Enter)", None))
        self.pbGo.setText(_translate("MainWindow", "Go", None))
        self.pbGo.setShortcut(_translate("MainWindow", "Ctrl+Return", None))
        self.rbAbsolute.setText(_translate("MainWindow", "Absolute:", None))
        self.groupBox_shortcuts.setTitle(_translate("MainWindow", "Shortcuts", None))
        self.pbGoRightLimit.setToolTip(_translate("MainWindow", "Go to Right Limit", None))
        self.pbGoPlatform.setToolTip(_translate("MainWindow", "Go to Platform", None))
        self.pbGoLeftLimit.setToolTip(_translate("MainWindow", "Go to Left Limit", None))
        self.pbHalt.setToolTip(_translate("MainWindow", "Halt Axis (Ctrl+Backspace)", None))
        self.pbHalt.setText(_translate("MainWindow", "Halt", None))
        self.label_3.setText(_translate("MainWindow", "Velocity (m/s):", None))
        self.label_2.setText(_translate("MainWindow", "Target (m):", None))
        self.label_4.setText(_translate("MainWindow", "Acc./Dec. (m/s²):", None))
        self.traverseOff.setText(_translate("MainWindow", "Off", None))
        self.traverse1m.setText(_translate("MainWindow", "1 m", None))
        self.traverse2m.setText(_translate("MainWindow", "2 m", None))
        self.traverse3m.setText(_translate("MainWindow", "3 m", None))
        self.traverse4m.setText(_translate("MainWindow", "4 m", None))
        self.actionWiki.setText(_translate("MainWindow", "Tow Tank Wiki", None))
        self.actionWiki.setShortcut(_translate("MainWindow", "F1", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.traverseCustom.setText(_translate("MainWindow", "Custom", None))
        self.actionRunHoming.setText(_translate("MainWindow", "Run Homing", None))
        self.actionRunHoming.setShortcut(_translate("MainWindow", "Ctrl+Shift+H", None))
        self.actionOverride.setText(_translate("MainWindow", "Override", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.enableAxis.setText(_translate("MainWindow", "Enable", None))
        self.enableAxis.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enable or Disable Axis (Ctrl+E)</p></body></html>", None))
        self.enableAxis.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.actionViewTowAxis.setText(_translate("MainWindow", "Tow Axis", None))
        self.actionViewTraverseAxes.setText(_translate("MainWindow", "Traverse Axes", None))
        self.actionTurbine_Axis.setText(_translate("MainWindow", "Turbine Axis", None))
        self.actionWave_Maker.setText(_translate("MainWindow", "Wave Maker", None))
        self.actionWave_Maker.setToolTip(_translate("MainWindow", "Some day...", None))
        self.actionHalt.setText(_translate("MainWindow", "Halt", None))
        self.actionHalt.setToolTip(_translate("MainWindow", "Halt Axis (Ctrl+Backspace)", None))
        self.actionHalt.setShortcut(_translate("MainWindow", "Ctrl+Backspace", None))
        self.actionJogPendant.setText(_translate("MainWindow", " Pendant", None))
        self.actionJogPendant.setToolTip(_translate("MainWindow", "Jog Pendant", None))
        self.actionTweet_On_PTP.setText(_translate("MainWindow", "On PTP", None))
        self.actionTweet_On_Jog.setText(_translate("MainWindow", "On Jog", None))
        self.actionTweet_On_Enable_Disable.setText(_translate("MainWindow", "On Enable/Disable", None))

import tow_resources_rc
